version: "3.6"

services:
    rabbitmq:
         container_name: "my-rabbitmq"
         hostname: rabbit
         image: masstransit/rabbitmq
         environment:
            - RABBITMQ_DEFAULT_USER=test
            - RABBITMQ_DEFAULT_PASS=test
         ports:
            - "5672:5672"
            - "15672:15672"
         restart: on-failure