version: '3.4'

services:
  mydummyapplication:
    image: ${DOCKER_REGISTRY-}mydummyapplication
    build:
      context: .
      dockerfile: Dockerfile

  rabbitmq:
    container_name: "my-rabbitmq"
    hostname: rabbit
    image: masstransit/rabbitmq
    environment:
       - RABBITMQ_DEFAULT_USER=test
       - RABBITMQ_DEFAULT_PASS=test
    ports:
       - "5672:5672"
       - "15672:15672"
    restart: on-failure
